/**
 * TradeExportModal — multi-step modal for generating a shareable trade list.
 *
 * Step 1 (select): pick which items to include, optionally filter by tag.
 * Step 2 (preview): show the formatted text, copy or share via native sheet.
 */

import * as Haptics from 'expo-haptics';
import { useEffect, useMemo, useState } from 'react';
import {
  Modal,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Chip } from '@/components/ember/Chip';
import { EmberBG } from '@/components/ember/EmberBG';
import { EmberBtn } from '@/components/ember/EmberBtn';
import { Rule } from '@/components/ember/Rule';
import { SectionHead } from '@/components/ember/SectionHead';
import { getItemById } from '@/lib/itemIndex';
import {
  categoryColor,
  colors,
  fontSize,
  radius,
  spacing,
  typography,
} from '@/lib/theme';
import type {
  Container,
  ItemCategory,
  ItemEntry,
  ItemRecord,
} from '@/lib/types';

interface Props {
  visible: boolean;
  container: Container;
  items: ItemRecord[];
  tagsByItem: Record<string, string[]>;
  onClose: () => void;
}

type Step = 'select' | 'preview';

const CATEGORY_ORDER: ItemCategory[] = [
  'unique',
  'set',
  'runeword',
  'base',
  'rune',
  'gem',
  'misc',
];

const CATEGORY_HEADINGS: Record<ItemCategory, string> = {
  unique: 'Uniques',
  set: 'Sets',
  runeword: 'Runewords',
  base: 'Bases',
  rune: 'Runes',
  gem: 'Gems',
  misc: 'Misc',
};

function classLabel(container: Container): string {
  if (container.type === 'shared_stash') return 'Shared Stash';
  const parts: string[] = [];
  if (container.class) parts.push(container.class);
  if (container.level) parts.push(`Lv ${container.level}`);
  return parts.join(', ');
}

function formatExport(
  container: Container,
  selected: Array<{ item: ItemRecord; entry: ItemEntry }>,
): string {
  const lines: string[] = [];
  const header = `=== TRADE LIST - ${container.name}`;
  const meta = classLabel(container);
  lines.push(meta ? `${header} (${meta}) ===` : `${header} ===`);
  lines.push('');

  const groups: Partial<Record<ItemCategory, Array<{ item: ItemRecord; entry: ItemEntry }>>> = {};
  for (const row of selected) {
    const cat = row.entry.category;
    if (!groups[cat]) groups[cat] = [];
    groups[cat]!.push(row);
  }

  for (const cat of CATEGORY_ORDER) {
    const group = groups[cat];
    if (!group || group.length === 0) continue;
    lines.push(`${CATEGORY_HEADINGS[cat]}:`);
    for (const { item, entry } of group) {
      const parts: string[] = [];
      if (item.sockets != null) parts.push(`${item.sockets}os`);
      if (item.notes) parts.push(item.notes);
      const stats = parts.length > 0 ? ` (${parts.join(', ')})` : '';
      const qty = item.quantity > 1 ? ` x${item.quantity}` : '';
      const loc = item.location ? ` - ${item.location}` : '';
      lines.push(`• ${entry.name}${stats}${qty}${loc}`);
    }
    lines.push('');
  }

  lines.push('=== Generated by Hoard ===');
  return lines.join('\n');
}

export function TradeExportModal({
  visible,
  container,
  items,
  tagsByItem,
  onClose,
}: Props) {
  const [step, setStep] = useState<Step>('select');
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [tagFilter, setTagFilter] = useState<string | null>(null);

  const itemsWithEntries = useMemo(
    () =>
      items
        .map((i) => ({ item: i, entry: getItemById(i.itemIndexId) }))
        .filter(
          (x): x is { item: ItemRecord; entry: ItemEntry } => !!x.entry,
        ),
    [items],
  );

  const availableTags = useMemo(() => {
    const set = new Set<string>();
    for (const tags of Object.values(tagsByItem)) {
      for (const t of tags) set.add(t);
    }
    return Array.from(set).sort();
  }, [tagsByItem]);

  const visibleItems = useMemo(() => {
    if (!tagFilter) return itemsWithEntries;
    return itemsWithEntries.filter((x) =>
      tagsByItem[x.item.id]?.includes(tagFilter),
    );
  }, [itemsWithEntries, tagFilter, tagsByItem]);

  useEffect(() => {
    if (visible) {
      setStep('select');
      setSelectedIds(new Set());
      setTagFilter(null);
    }
  }, [visible]);

  const toggle = (id: string) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(
      () => undefined,
    );
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const selectAllVisible = () => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      for (const x of visibleItems) next.add(x.item.id);
      return next;
    });
  };

  const deselectAll = () => {
    setSelectedIds(new Set());
  };

  const previewText = useMemo(() => {
    const chosen = itemsWithEntries.filter((x) => selectedIds.has(x.item.id));
    return formatExport(container, chosen);
  }, [container, itemsWithEntries, selectedIds]);

  const handleShare = async () => {
    try {
      await Share.share({
        title: `${container.name} — Trade List`,
        message: previewText,
      });
    } catch {
      // Cancelled or unavailable — leave modal open.
    }
  };

  const handleCopy = async () => {
    // Clipboard isn't bundled; fall back to the native share sheet where
    // users can pick "Copy" on both iOS and Android.
    await handleShare();
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <View style={styles.container}>
        <EmberBG />
        <SafeAreaView style={{ flex: 1 }} edges={['top', 'left', 'right']}>
          <View style={styles.header}>
            <View style={{ flex: 1 }}>
              <SectionHead eyebrow="Market" title="TRADE EXPORT" />
            </View>
            <Pressable onPress={onClose} style={styles.closeBtn} hitSlop={8}>
              <Text style={styles.closeText}>Close</Text>
            </Pressable>
          </View>

          {step === 'select' ? (
            <View style={styles.flex}>
              <View style={styles.controls}>
                <Text style={styles.subtitle}>
                  Choose items to include from {container.name}.
                </Text>

                {availableTags.length > 0 ? (
                  <View style={styles.tagRowWrap}>
                    <ScrollView
                      horizontal
                      showsHorizontalScrollIndicator={false}
                      contentContainerStyle={styles.tagRow}
                      style={{ flexGrow: 0 }}
                    >
                      <Chip
                        label="All Items"
                        active={!tagFilter}
                        onPress={() => setTagFilter(null)}
                      />
                      {availableTags.map((t) => (
                        <Chip
                          key={t}
                          label={t}
                          color={colors.gold}
                          active={tagFilter === t}
                          onPress={() =>
                            setTagFilter(tagFilter === t ? null : t)
                          }
                        />
                      ))}
                    </ScrollView>
                  </View>
                ) : null}

                <View style={styles.selectActions}>
                  <View style={styles.selectBtn}>
                    <EmberBtn
                      size="sm"
                      variant="ghost"
                      full
                      onPress={selectAllVisible}
                    >
                      {`Select ${visibleItems.length}`}
                    </EmberBtn>
                  </View>
                  <View style={styles.selectBtn}>
                    <EmberBtn
                      size="sm"
                      variant="outline"
                      full
                      onPress={deselectAll}
                    >
                      Clear
                    </EmberBtn>
                  </View>
                </View>
              </View>

              <ScrollView contentContainerStyle={styles.itemsList}>
                {visibleItems.length === 0 ? (
                  <Text style={styles.empty}>No matching items.</Text>
                ) : (
                  visibleItems.map(({ item, entry }) => {
                    const checked = selectedIds.has(item.id);
                    return (
                      <Pressable
                        key={item.id}
                        style={[
                          styles.selectRow,
                          checked && styles.selectRowActive,
                        ]}
                        onPress={() => toggle(item.id)}
                      >
                        <View
                          style={[
                            styles.checkbox,
                            checked && styles.checkboxChecked,
                          ]}
                        >
                          {checked ? <Text style={styles.check}>✓</Text> : null}
                        </View>
                        <View style={{ flex: 1 }}>
                          <Text
                            style={[
                              styles.itemName,
                              { color: categoryColor(entry.category) },
                            ]}
                            numberOfLines={1}
                          >
                            {entry.name}
                          </Text>
                          {item.notes ? (
                            <Text style={styles.itemNotes} numberOfLines={1}>
                              {item.notes}
                            </Text>
                          ) : null}
                        </View>
                      </Pressable>
                    );
                  })
                )}
              </ScrollView>

              <View style={styles.footer}>
                <View style={styles.footerBtn}>
                  <EmberBtn
                    variant="outline"
                    size="sm"
                    full
                    onPress={onClose}
                  >
                    Cancel
                  </EmberBtn>
                </View>
                <View style={styles.footerBtn}>
                  <EmberBtn
                    size="sm"
                    full
                    disabled={selectedIds.size === 0}
                    onPress={() => setStep('preview')}
                  >
                    {`Preview (${selectedIds.size})`}
                  </EmberBtn>
                </View>
              </View>
            </View>
          ) : (
            <View style={styles.flex}>
              <View style={styles.previewHead}>
                <Rule label="Preview" accent={colors.ember} />
              </View>
              <ScrollView contentContainerStyle={styles.previewWrap}>
                <Text style={styles.previewText} selectable>
                  {previewText}
                </Text>
              </ScrollView>

              <View style={styles.footer}>
                <View style={styles.footerBtn}>
                  <EmberBtn
                    variant="outline"
                    size="sm"
                    full
                    onPress={() => setStep('select')}
                  >
                    Back
                  </EmberBtn>
                </View>
                <View style={styles.footerBtn}>
                  <EmberBtn
                    variant="ghost"
                    size="sm"
                    full
                    onPress={handleCopy}
                  >
                    Copy
                  </EmberBtn>
                </View>
                <View style={styles.footerBtn}>
                  <EmberBtn size="sm" full onPress={handleShare}>
                    Share
                  </EmberBtn>
                </View>
              </View>
            </View>
          )}
        </SafeAreaView>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  flex: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  closeBtn: {
    padding: spacing.sm,
  },
  closeText: {
    color: colors.ember,
    fontFamily: typography.monoBold,
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  controls: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    gap: spacing.sm,
  },
  subtitle: {
    color: colors.textMuted,
    fontFamily: typography.mono,
    fontSize: 11,
    letterSpacing: 1.2,
  },
  tagRowWrap: {
    flexShrink: 0,
  },
  tagRow: {
    gap: 6,
    paddingVertical: spacing.xs,
  },
  selectActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  selectBtn: {
    flex: 1,
  },
  itemsList: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: 4,
  },
  selectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.card,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  selectRowActive: {
    borderColor: colors.ember,
    backgroundColor: colors.cardHi,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.textMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.ember,
    borderColor: colors.ember,
  },
  check: {
    color: '#120905',
    fontWeight: '700',
    fontSize: 14,
  },
  itemName: {
    fontFamily: typography.displaySemi,
    fontSize: fontSize.md,
    letterSpacing: 1,
  },
  itemNotes: {
    color: colors.textMuted,
    fontFamily: typography.hand,
    fontSize: fontSize.sm,
    fontStyle: 'italic',
    marginTop: 2,
  },
  empty: {
    color: colors.textMuted,
    fontFamily: typography.hand,
    fontSize: fontSize.md,
    fontStyle: 'italic',
    textAlign: 'center',
    padding: spacing.xl,
  },
  footer: {
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  footerBtn: {
    flex: 1,
  },
  previewHead: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  previewWrap: {
    padding: spacing.lg,
  },
  previewText: {
    color: colors.text,
    fontFamily: typography.mono,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.5,
    backgroundColor: colors.bgSoft,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
});
